#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Спецификации всех модулей SHARD Enterprise.
Каждая запись описывает: как импортировать, как сконфигурировать и от чего зависит модуль.
"""

from typing import Dict, List, Optional, Any

MODULE_SPECS: Dict[str, Dict[str, Any]] = {
    # === ML модули ===
    'attention_lstm': {
        'import_path': 'shard_attention_lstm',
        'class': 'ShardAttentionLSTMIntegration',
        'config_class': 'AttentionLSTMConfig',
        'config_overrides': {'sequence_length': 'ml.dl_sequence_length'},
        'dependencies': [],
        'category': 'ml',
        'start_method': None,
    },
    'temporal_gnn': {
        'import_path': 'shard_temporal_gnn',
        'class': 'TemporalGNNEngine',
        'config_class': 'TemporalGNNConfig',
        'config_overrides': {},
        'dependencies': [],
        'category': 'ml',
        'start_method': None,
    },
    'contrastive_vae': {
        'import_path': 'shard_contrastive_vae',
        'class': 'ShardContrastiveVAEIntegration',
        'config_class': 'ContrastiveVAEConfig',
        'config_overrides': {},
        'dependencies': [],
        'category': 'ml',
        'start_method': 'start',
    },
    'federated': {
        'import_path': 'shard_federated',
        'class': 'ShardFederatedV2Integration',
        'config_class': 'FederatedConfig',
        'config_overrides': {},
        'dependencies': [],
        'category': 'ml',
        'start_method': 'start',
        'config_arg': 'federated.mode',
    },
    'rl_defense': {
        'import_path': 'shard_rl_defense',
        'class': 'ShardRLDefenseIntegration',
        'config_class': 'RLDefenseConfig',
        'config_overrides': {},
        'dependencies': [],
        'category': 'ml',
        'start_method': 'start',
        'start_kwargs': {'train': 'rl_defense.train'},
    },
    'cloud_security': {
        'import_path': 'shard_cloud_security',
        'class': 'ShardCloudSecurityIntegration',
        'config_class': 'CloudSecurityConfig',
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': 'start',
        'constructor_args': ['config', 'event_bus', 'logger_service'],
    },
    'adaptive_learning': {
        'import_path': 'shard_adaptive_learning',
        'class': 'AdaptiveLearningEngine',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'ml',
        'start_method': None,
        'custom_init': 'adaptive_learning',
    },
    'autonomous_group': {
        'import_path': None,
        'class': None,
        'is_group': True,
        'members': {
            'shard_autonomous_response': ['ShardAutonomousIntegration'],
            'shard_defense_pipeline_v3': ['ShardDefensePipeline'],
            'shard_anomaly_detector': ['ShardAnomalyDetector'],
            'shard_gnn_integration': ['ShardGNN'],
            'shard_fusion_integration': ['ShardFusion'],
            'shard_temporal_integration': ['ShardTemporalGNN'],
            'shard_automl': ['AutoMLSelector', 'select_model_for_attack', 'record_model_result'],
            'shard_swagger_api': ['start_api_server'],
        },
        'category': 'core',
    },
    'llm_guardian': {
        'import_path': 'shard_llm_guardian',
        'class': 'ShardLLMGuardianIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': None,
        'setup_args': ['event_bus', 'logger'],
    },
    'code_security': {
        'import_path': 'shard_code_security',
        'class': 'ShardCodeSecurityIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'cve_intelligence': {
        'import_path': 'shard_cve_intelligence',
        'class': 'ShardCVEIntelligenceIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'red_team': {
        'import_path': 'shard_red_team',
        'class': 'ShardRedTeamIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'offensive',
        'start_method': None,
        'setup_args': ['event_bus', 'logger'],
    },
    'threat_hunting': {
        'import_path': 'shard_threat_hunting',
        'class': 'ShardThreatHuntingIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'deception': {
        'import_path': 'shard_deception_technology',
        'class': 'ShardDeceptionIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'security',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'soar': {
        'import_path': 'shard_soar',
        'class': 'ShardSOARIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'orchestration',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger', 'firewall'],
    },
    'forensics': {
        'import_path': 'shard_digital_forensics',
        'class': 'ShardForensicsIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'forensics',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'mitre': {
        'import_path': 'shard_mitre_attack',
        'class': 'ShardMITREIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'intelligence',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
    'tip': {
        'import_path': 'shard_tip',
        'class': 'ShardTIPIntegration',
        'config_class': None,
        'config_overrides': {},
        'dependencies': [],
        'category': 'intelligence',
        'start_method': 'start',
        'setup_args': ['event_bus', 'logger'],
    },
}

MODULES_WITH_SETUP = [
    'llm_guardian', 'code_security', 'cve_intelligence', 'red_team',
    'threat_hunting', 'deception', 'soar', 'forensics', 'mitre', 'tip'
]

MODULES_WITH_STOP = [
    'attention_lstm', 'contrastive_vae', 'federated', 'rl_defense',
    'cloud_security', 'code_security', 'cve_intelligence', 'threat_hunting',
    'deception', 'soar', 'forensics', 'mitre', 'tip'
]
