{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shard-enterprise.fullname" . }}-data
  labels:
    {{- include "shard-enterprise.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shard-enterprise.fullname" . }}-models
  labels:
    {{- include "shard-enterprise.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shard-enterprise.fullname" . }}-logs
  labels:
    {{- include "shard-enterprise.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: { { .Values.persistence.logs.size } }
{ { - end } }