apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shard-enterprise.fullname" . }}-secrets
  labels:
    {{- include "shard-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  abuseipdb-key: {{ .Values.config.secrets.abuseipdb_key | quote }}
  virustotal-key: {{ .Values.config.secrets.virustotal_key | quote }}
  ldap-bind-password: {{ .Values.config.secrets.ldap_bind_password | quote }}
  grafana-api-key: {{ .Values.config.secrets.grafana_api_key | quote }}
  federated-auth-token: {{ .Values.federated.server.authToken | quote }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | quote }}
  {{- end }}