#!/bin/bash
echo "=============================================="
echo "🔑 Настройка Threat Intelligence API ключей"
echo "=============================================="
echo ""
echo "Получи бесплатные ключи:"
echo "  1. AbuseIPDB: https://www.abuseipdb.com/register"
echo "     Бесплатно: 1000 проверок/день"
echo ""
echo "  2. VirusTotal: https://www.virustotal.com/gui/join-us"
echo "     Бесплатно: 500 проверок/день"
echo ""
echo "  3. IPinfo: https://ipinfo.io/signup"
echo "     Бесплатно: 50K запросов/месяц"
echo ""
echo "После получения ключей, экспортируй их:"
echo "  export ABUSEIPDB_KEY=your_key_here"
echo "  export VIRUSTOTAL_KEY=your_key_here"
echo "  export IPINFO_TOKEN=your_token_here"
echo ""
echo "Или добавь в config.yaml:"
echo "  threat_intel:"
echo "    abuseipdb_key: 'your_key'"
echo "    virustotal_key: 'your_key'"
echo "    ipinfo_token: 'your_token'"
